name: build

on: [push]

permissions:
  contents: read
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, macos-15-intel, windows-latest ]
    name: build ${{ matrix.os }}

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: Set up JDK
      uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
      with:
        java-version: '25'
        distribution: 'liberica'
        java-package: 'jdk+fx'
        cache: 'maven'
    - name: Install gettext and xvfb on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y gettext

    - name: Build with Maven Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: xvfb-run mvn -Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw --batch-mode --update-snapshots verify

    - name: Build with Maven MacOS intel
      if: matrix.os == 'macos-15-intel'
      run: mvn --batch-mode --update-snapshots -DskipTests verify

    - name: Install scoop on Windows
      if: matrix.os == 'windows-latest'
      uses: MinoruSekine/setup-scoop@6435f41324fa55988d8ce5b06bae5cafc75fe045 # v4

    - name: Install gettext on Windows
      if: matrix.os == 'windows-latest'
      run: scoop install gettext

    - name: Build with Maven
      if: matrix.os != 'ubuntu-latest' && matrix.os != 'macos-15-intel'
      run: mvn --batch-mode --update-snapshots verify
